markdown: kramdown
# kramdown : markdown의 개조판.
# markdown에서 불편한 사항을 개선한 형태

# Website info
title: "IT Blog"
# 자신의 blog title.

baseurl: /

description: "Development & Technical Training"
# blog home에 표시될 blog에 대한 전반적인 설명.

#cover: assets/built/images/blog-cover.png
# blog home에 표시될 blog cover image.

#logo:
#logo_dark:

#favicon: assets/built/images/favicon.jpg
# favicon으로 사용할 image

# Social info
navigation: True
# Navigation bar link를 보여줄건지 여부

#subscribers: True
# subscriber 기능을 사용할건지의 여부
# 저는 약간의 수정을 통해 subscriber 기능대신
# lunr.js를 이용한 검색 기능으로 대체 사용했습니다.
# 검색기능으로 대체하기 위해서
# `_includes/subscribe-form.html` 파일의 수정이 필요합니다

twitter:
facebook:
# 만약 twitter와 facebook을 이용하면 username을 입력

# Disqus
disqus: True
disqus_shortname: sunghoons-blog
# disqus는 온라인 댓글 시스템. 댓글 기능을 사용하기 위해
# disqus를 이용할 것인지 여부와 만약 사용하면
# disqus shortname을 입력 ( disqus username이 아님 )


# Google Analytics
#google_analytics:  # replace with your GA tracking identifier
# Google Analytics을 사용할 경우 GA tracking identifier를 입력

# Permalinks
#permalink: /:title
# permalink: /author/:author
# permalink: /tag/:title
# 각각의 post에 고정주소를 어떤 방식으로 할당할 것인지를 결정
# 이 값을 바꾸면 작성한 포스트의 저장위치나 파일이름이 변경된다.

# gems and other configs
#plugins: [jekyll-paginate, jekyll-feed, jekyll-gist]
#exclude: [vendor]

#feed:
#  path: feed.xml

# Travis-CI 설정입니다.
#safe: False
#lsi: False

#username: moon9342
#repo: GitHubPageMaker
# username : travis-ci와 연동하는 github의 username
# repo: travis-ci와 연동하는 github의 repository이름
# https://github.com/<username>/<repository>

#branch: master
# 사용할 branch명

#relative_source: 

#destination: ./output/
# compile된 결과가 생성되는 폴더
# 이 폴더안으로 우리가 운영하는 블로그 내용이 컴파일되서 들어간다.
# 이 폴더안의 내용을 github repository(https://username.github.io)에 push
# 만약 Travis-CI를 이용할 예정이면 이 부분을 git submodule로
# github repository(https://username.github.io)에 연결해야 한다.

#production_url:  https://moon9342.github.io/
#source_url:  https://github.com/moon9342/GitHubPageMaker/

# exclude는 Jekyll컴파일 시 destination에 포함될 필요가
# 없는것들을 명시한다. (node_modules는 포함시키자)
#exclude:
#  - README.md
#  - Rakefile
#  - Gemfile
#  - Gemfile.lock
#  - changelog.md
#  - "*.Rmd"
#  - vendor
#  - .travis.yml
#  - node_modules